# Generated by Django 3.1.4 on 2021-01-07 09:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20210107_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 7, 15, 29, 37, 424583)),
        ),
    ]
